# Generated by Django 2.2 on 2019-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_aplication_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heroinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('hage', models.IntegerField(default=18)),
                ('hcontent', models.CharField(max_length=40)),
                ('hbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curd.Bookinfo')),
            ],
        ),
    ]
